language: node_js
node_js:
  - "node"
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run importdata
  - yarn run prep
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: spectrum-css
  on:
    branch: nextjs
