name: Deploy Docs

on:
  push:
    branches: nextjs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: nextjs
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: <registry url>
    - name: install
      run: yarn install --ignore-optional
    - name: build
      run: |
        npm run prep
    - name: deploy
      run: |
        npm run deploy
      env:
        CI: true
